### ISSUE TITLE
Net

### ISSUE THREAD

**Issue by Morturg** [Dogfisc/combat-modifier-calc#9]
- Net, has maximum range increment of 1, not 5 as per thrown (it's specified on the item it's self) 

- normally the maximum range is the ranged increment x 5 with thrown weapons

- specifically states on Net item, that it's maximum range is 10ft
- thus, that static value needs to change in the array

**Comment by bmos** [comment]
> A net is used to entangle enemies. When you throw a net, you make a ranged touch attack against your target. A net’s maximum range is 10 feet. If you hit, the target is entangled. An entangled creature takes a –2 penalty on attack rolls and a –4 penalty to Dexterity, can move at only half speed, and cannot charge or run. If you control the trailing rope by succeeding at an opposed Strength check while holding it, the entangled creature can move only within the limits that the rope allows. If the entangled creature attempts to cast a spell, it must succeed at a concentration check with a DC of 15 + the spell’s level or be unable to cast the spell.

> An entangled creature can escape with a successful DC 20 Escape Artist check (a full-round action). The net has 5 hit points and can be burst with a successful DC 25 Strength check (also a full-round action). A net is useful only against creatures within one size category of you.

> A net must be folded to be thrown effectively. The first time you throw your net in a fight, you make a normal ranged touch attack roll. After the net is unfolded, you take a –4 penalty on attack rolls with it. It takes 2 rounds for a proficient user to fold a net and twice that long for a nonproficient one to do so.

**Comment by bmos** [comment]
I agree with your interpretation @Morturg .
